const PendingData = [
  {
    id: 1,
    name: "SoftCentric",
    status: "Active",
    industry: "Software Development",
    owner: "Rana Umair",
    size: "20 Employees",
    package: "Premium",
    amount: "$100",
    location: "Arifwala",
    requestDate: "28 Jul 2026",
  },
  {
    id: 2,
    name: "TechVision",
    status: "Active",
    industry: "Web Development",
    owner: "Ali Ahmed",
    size: "35 Employees",
    package: "Business",
    amount: "$200",
    location: "Lahore",
    requestDate: "29 Jul 2026",
  },
  {
    id: 3,
    name: "Finance Pro",
    status: "Active",
    industry: "Finance",
    owner: "Hamza Ali",
    size: "50 Employees",
    package: "Enterprise",
    amount: "$300",
    location: "Karachi",
    requestDate: "30 Jul 2026",
  },
];

export default PendingData;