const subscriptionData = [
  {
    id: 1,
    company: "SoftCentric",
    status: "Free",
    plan: "Pro",
    duration: "1 Year",
    date: "Jan 1, 2024",
    date2:"Jan 1 2025",
    owner: "umair@gmail.com",
    action: "Pro",
  },
   {
    id: 1,
    company: "SoftCentric",
    status: "Free",
    plan: "Pro",
    duration: "1 Year",
    date: "Jan 1, 2024",
    date2:"Jan 1 2025",
    owner: "umair@gmail.com",
    action: "Pro",
  },
   {
    id: 1,
    company: "SoftCentric",
    status: "Free",
    plan: "Pro",
    duration: "1 Year",
    date: "Jan 1, 2024",
    date2:"Jan 1 2025",
    owner: "umair@gmail.com",
    action: "Pro",
  },
   {
    id: 1,
    company: "SoftCentric",
    status: "Free",
    plan: "Pro",
    duration: "1 Year",
    date: "Jan 1, 2024",
    date2:"Jan 1 2025",
    owner: "umair@gmail.com",
    action: "Pro",
  },
   {
    id: 1,
    company: "SoftCentric",
    status: "Free",
    plan: "Pro",
    duration: "1 Year",
    date: "Jan 1, 2024",
    date2:"Jan 1 2025",
    owner: "umair@gmail.com",
    action: " Pro",
  },
 
];

export default subscriptionData;