import { useState } from "react";
import { Download } from "lucide-react";

const typeStyles = {
  Progress: "bg-indigo-50 text-indigo-600",
  Summary: "bg-emerald-50 text-emerald-600",
  Performance: "bg-amber-50 text-amber-600",
  Overview: "bg-blue-50 text-blue-600",
};

const VISIBLE_LIMIT = 4;

function downloadReport(report) {
  const content = `Report: ${report.name}\nProject: ${report.project}\nGenerated By: ${report.generatedBy}\nDate: ${report.date}\nType: ${report.type}\n`;
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.name.replace(/\s+/g, "-")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ReportsTable({ reports }) {
  const [showAll, setShowAll] = useState(false);
  const visibleReports = showAll ? reports : reports.slice(0, VISIBLE_LIMIT);

  return (
    <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
      <p className="text-sm font-medium text-slate-700 mb-4">Recent Reports</p>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-slate-400 text-xs uppercase tracking-wide">
              <th className="pb-2 font-medium">Report Name</th>
              <th className="pb-2 font-medium">Project</th>
              <th className="pb-2 font-medium">Generated By</th>
              <th className="pb-2 font-medium">Date</th>
              <th className="pb-2 font-medium">Type</th>
              <th className="pb-2 font-medium">Action</th>
            </tr>
          </thead>
          <tbody>
            {visibleReports.length === 0 && (
              <tr>
                <td colSpan={6} className="py-6 text-center text-slate-400 text-sm">
                  No reports in this date range.
                </td>
              </tr>
            )}
            {visibleReports.map((r) => (
              <tr key={r.id} className="border-t border-slate-50">
                <td className="py-3 text-slate-700 font-medium">{r.name}</td>
                <td className="py-3 text-slate-500">{r.project}</td>
                <td className="py-3 text-slate-500">{r.generatedBy}</td>
                <td className="py-3 text-slate-500">{r.date}</td>
                <td className="py-3">
                  <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${typeStyles[r.type]}`}>
                    {r.type}
                  </span>
                </td>
                <td className="py-3">
                  <button
                    onClick={() => downloadReport(r)}
                    className="text-slate-400 hover:text-slate-600"
                    aria-label={`Download ${r.name}`}
                  >
                    <Download size={16} />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {reports.length > VISIBLE_LIMIT && (
        <div className="text-center mt-4">
          <button
            onClick={() => setShowAll((v) => !v)}
            className="text-sm text-indigo-600 hover:underline"
          >
            {showAll ? "Show Less ↑" : "View All Reports →"}
          </button>
        </div>
      )}
    </div>
  );
}