import { useState } from "react";
import { Calendar, Download, ChevronDown, Check, Search } from "lucide-react";
import StatCardSimple from "../components/Cards/StatCardSimple";
import DonutChart from "../components/Charts/DonutChart";
import BarChart from "../components/Charts/BarChart";
import ReportsTable from "../components/Tables/ReportsTable";
import { useReportsData } from "../hooks/useReportsData";

function DateRangeButton({ start, end, onApply }) {
  const [open, setOpen] = useState(false);
  const [tempStart, setTempStart] = useState(start);
  const [tempEnd, setTempEnd] = useState(end);

  function apply() {
    onApply(tempStart, tempEnd);
    setOpen(false);
  }

  const label = `${new Date(start).toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" })} - ${new Date(end).toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" })}`;

  return (
    <div className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-2 text-sm border border-slate-200 rounded-lg px-3 py-2 text-slate-600 bg-white"
      >
        <Calendar size={14} /> {label}
      </button>
      {open && (
        <div className="absolute right-0 mt-1 bg-white border border-slate-200 rounded-lg shadow-lg z-10 p-4 w-64">
          <label className="text-xs text-slate-500 block mb-1">Start Date</label>
          <input
            type="date"
            value={tempStart}
            onChange={(e) => setTempStart(e.target.value)}
            className="w-full border border-slate-200 rounded-lg text-sm px-2 py-1.5 mb-3"
          />
          <label className="text-xs text-slate-500 block mb-1">End Date</label>
          <input
            type="date"
            value={tempEnd}
            onChange={(e) => setTempEnd(e.target.value)}
            className="w-full border border-slate-200 rounded-lg text-sm px-2 py-1.5 mb-3"
          />
          <button
            onClick={apply}
            className="w-full bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium py-1.5 rounded-lg"
          >
            Apply
          </button>
        </div>
      )}
    </div>
  );
}

function GroupByDropdown({ value, onChange }) {
  const [open, setOpen] = useState(false);
  const options = [
    { key: "project", label: "By Project" },
    { key: "team", label: "By Team Member" },
  ];
  const activeLabel = options.find((o) => o.key === value)?.label;

  return (
    <div className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-1 text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 text-slate-500"
      >
        {activeLabel} <ChevronDown size={12} />
      </button>
      {open && (
        <div className="absolute right-0 mt-1 w-40 bg-white border border-slate-200 rounded-lg shadow-lg z-10 py-1">
          {options.map((o) => (
            <button
              key={o.key}
              onClick={() => {
                onChange(o.key);
                setOpen(false);
              }}
              className="w-full flex items-center justify-between px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-50"
            >
              {o.label}
              {value === o.key && <Check size={14} className="text-indigo-600" />}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function exportReportsCSV(reports) {
  const header = "Report Name,Project,Generated By,Date,Type\n";
  const rows = reports
    .map((r) => `${r.name},${r.project},${r.generatedBy},${r.date},${r.type}`)
    .join("\n");
  const blob = new Blob([header + rows], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "reports.csv";
  a.click();
  URL.revokeObjectURL(url);
}

export default function Reports() {
  const { data, loading, error } = useReportsData();
  const [dateRange, setDateRange] = useState({ start: "2025-06-01", end: "2025-06-30" });
  const [groupBy, setGroupBy] = useState("project");
  const [search, setSearch] = useState("");

  if (loading) return <div className="p-6 text-slate-500 text-sm">Loading reports…</div>;
  if (error) return <div className="p-6 text-rose-500 text-sm">Failed to load reports.</div>;

  const { stats, statusBreakdown, projectProgress, teamProgress, reports } = data;

  const query = search.trim().toLowerCase();

  const filteredReports = reports.filter((r) => {
    const inDateRange = r.isoDate >= dateRange.start && r.isoDate <= dateRange.end;
    const matchesSearch =
      query === "" ||
      r.name.toLowerCase().includes(query) ||
      r.project.toLowerCase().includes(query);
    return inDateRange && matchesSearch;
  });

  const barData = groupBy === "project" ? projectProgress : teamProgress;

  return (
    <div className="min-h-screen bg-slate-50 p-6 space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-semibold text-slate-800">Reports</h1>
          <p className="text-sm text-slate-500 mt-1">
            Track progress, performance and productivity across your projects.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <DateRangeButton
            start={dateRange.start}
            end={dateRange.end}
            onApply={(start, end) => setDateRange({ start, end })}
          />
          <button
            onClick={() => exportReportsCSV(filteredReports)}
            className="flex items-center gap-2 text-sm border border-indigo-200 text-indigo-600 rounded-lg px-3 py-2 bg-white"
          >
            <Download size={14} /> Export
          </button>
        </div>
      </div>

      <div className="relative max-w-sm">
        <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search by project or report name..."
          className="w-full pl-9 pr-3 py-2 text-sm border border-slate-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500/30"
        />
        {search && (
          <button
            onClick={() => setSearch("")}
            className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-slate-400 hover:text-slate-600"
          >
            Clear
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        {stats.map((s) => (
          <StatCardSimple key={s.id} {...s} />
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
          <p className="text-sm font-medium text-slate-700 mb-4">Task Status Overview</p>
          <DonutChart segments={statusBreakdown} />
        </div>

        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
          <div className="flex items-center justify-between mb-4">
            <p className="text-sm font-medium text-slate-700">Project Progress</p>
            <GroupByDropdown value={groupBy} onChange={setGroupBy} />
          </div>
          <BarChart data={barData} max={100} />
        </div>
      </div>

      <ReportsTable reports={filteredReports} />
    </div>
  );
}